credentials:
  usernames:
    dminango:
      email: pablodavid218@gmail.com
      name: David Minango
      password: $2b$12$5y90T8b/PrFN0mjZG2gie.hZkHTITSQVRbEEn0KyN0cLoZ0QSTIL6 # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: def # To be replaced with hashed password
cookie:
  expiry_days: 90
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - pablodavid218@gmail.com